### ISSUE TITLE
Answers disappeared

### ISSUE THREAD

**Issue by karafecho** [NCATS-Tangerine/tranql#2]
4/16/19: I changed several parameters and was able to run a query and generate results, although when I clicked on the resulting KG, everything disappeared. When I re-ran the query, all was fine, however.

**Comment by stevencox** [comment]
Yes, this is a bug. Moved into work queue.

**Comment by stevencox** [comment]
This is related to the lack of error messages. Verify, as #15 is completed, that this effect is no longer observed.
