### ISSUE TITLE
Character issues wrt queries

### ISSUE THREAD

**Issue by karafecho** [NCATS-Tangerine/tranql#3]
The main blocker I faced when attempting my own queries was inserting certain characters into the script. For instance, I can't insert " ^" without searching for ASCII code or something.

**Comment by stevencox** [comment]
When I
* Put my cursor in the query editor
* Depress the Shift key and the 6 key simultaneously

I get the "^" character.

What do you see?

**Comment by karafecho** [comment]
Oh, thanks. I didn't know how to insert special characters such as ^.

**Comment by karafecho** [comment]
Oh, yeah, ^ is on my keyboard. Who knew? :-)
