### ISSUE TITLE
Visualization Legend

### ISSUE THREAD

**Issue by karafecho** [NCATS-Tangerine/tranql#5]
Users need a key to interpret the results.

**Comment by stevencox** [comment]
We need a legend showing which colors apply to graph elements.
* First for nodes
* Then for links

**Comment by stevencox** [comment]
Something along these lines:

![image](https://user-images.githubusercontent.com/306971/58034405-85635800-7af4-11e9-80f3-78259b84fb76.png)

**Comment by stevencox** [comment]
@frostyfan109 implemented in his TranQL [fork](https://github.com/frostyfan109/tranql).

Pulled today and it works great.
