### ISSUE TITLE
Response Parsing Error

### ISSUE THREAD

**Issue by karafecho** [NCATS-Tangerine/tranql#54]
@YaphetKG @cnbennett3 @mmersmann : The following query ran prior to the holiday break, but now does not.

SELECT population_of_individual_organisms->disease->gene->chemical_substance
FROM "/schema"
WHERE icees.table = 'patient'
AND icees.year = 2010
AND icees.feature.EstResidentialDensity = 1
AND icees.maximum_p_value = 0.5

The following error is returned:

![image](https://user-images.githubusercontent.com/26254388/71687057-e5003200-2d6a-11ea-9733-84bb23e20c81.png)

**Comment by YaphetKG** [comment]
HI @karafecho , we were having some issues with our cluster, but now the servers are back up again. Try running the queries again.

**Comment by YaphetKG** [comment]
/graph/quick/gamma seems to not return anything for the second part of the query above, looking into it

**Comment by YaphetKG** [comment]
Robokop is now returning results too. It should be good now.

**Comment by karafecho** [comment]
Thanks, @YaphetKG. Queries are running now.

Note that ROBOKOP was running just fine yesterday at robokop.renci.org. Just an FYI...
