### ISSUE TITLE
Provenance of ICEES results and computation on output

### ISSUE THREAD

**Issue by karafecho** [NCATS-Tangerine/tranql#7]
Users need a way to view ICEES-specific results. In terms of what information to capture.

I'd suggest the following:

- ICEES query parameters

- ICEES output entities

- a computation to capture directionality of the effect; in other words, with the current functionality, a significant _P_ value indicates only that two groups are different, but it does not provide information on which group had more/less counts, for example; risk ratios and odds ratios are more informative, although this metric only makes sense for certain types of queries, such as ED visits for respiratory issues (e.g., relative risk of ED visits for respiratory issues is XXX for patients who receive drug YYY)

**Comment by stevencox** [comment]
Agreed that users do need these capabilities but this is not a TranQL feature.  i.e. TranQL cant implement data specific viewers for each reasoner it calls.

To do this we should create an issue for ICEES to make a viewer for a knowledge graph containing ICEES data. Then TranQL can use that viewer.

This is analogous to the way TranQL launches the Robokop answer viewer. And is likely the way for us to ultimately incorporate functionality like visualizing comparisons of answers.

**Comment by karafecho** [comment]
This makes sense to me, but in addition to an ICEES KG, I think users need to be able to view the output tables and perhaps export the JSON files. I assume this is something you will be discussing with Hao and/or  posting as an ICEES GitHub issue?

**Comment by stevencox** [comment]
Yes, let's discuss with @xu-hao. I'd like to figure out how to launch viewers on a KG generically - like the current answer viewer. Then we can create an issue for ICEES to design a specific one for ICEES as the next KG viewer.
