### ISSUE TITLE
Non-Green/Gamma Knowledge Sources

### ISSUE THREAD

**Issue by karafecho** [NCATS-Tangerine/tranql#8]
@stevencox @xu-hao : I think it would be great to be able to run queries using calls to IR's [GNBR reasoner](https://gnbr-dashboard.ncats.io/) and X-Ray's [RTX reasoner](https://rtx.ncats.io/overview.html). I also think it would be great to run queries using calls to [COHD](http://smart-api.info/) and [Clinical Profiles](https://github.com/NCATS-Tangerine/fhir_publish). I think we should focus on ICEES and Gamma initially, but calls to non-Green/Gamma Knowledge Sources should be something on our radar for WF4 and WF5.

**Comment by stevencox** [comment]
Same here - this is TranQL's purpose. An initial attempt to integrate RTX at the hackathon proved a bit early. Will circle back when the reasoner API is complete. In all cases, this is dependent on the existence of a viable implementation of the KGS standard.

The next one will be ICEES. The current implementation in TranQL is still a stub.

**Comment by stevencox** [comment]
Closing this issue. Creating a specific [issue for ICEES KGS API integration](https://github.com/NCATS-Tangerine/tranql/issues/9). Other reasoner specific tasks will be created as APIs become available.
